export const events = [
  {
    title: "Next.js Conf 2026",
    image: "/images/event1.png",
    slug: "nextjs-conf-2026",
    location: "San Francisco, CA",
    date: "2026-10-25",
    time: "09:00 AM",
  },
  {
    title: "React Summit",
    image: "/images/event2.png",
    slug: "react-summit",
    location: "Amsterdam, NL",
    date: "2026-06-14",
    time: "10:00 AM",
  },
  {
    title: "AI Hackathon: Future of Web",
    image: "/images/event3.png",
    slug: "ai-hackathon-2026",
    location: "New York, NY",
    date: "2026-05-12",
    time: "08:30 AM",
  },
  {
    title: "Node.js Interactive",
    image: "/images/event4.png",
    slug: "node-interactive",
    location: "Austin, TX",
    date: "2026-08-18",
    time: "09:30 AM",
  },
  {
    title: "Web Performance Workshop",
    image: "/images/event5.png",
    slug: "web-perf-workshop",
    location: "Remote",
    date: "2026-05-30",
    time: "11:00 AM",
  },
  {
    title: "TypeScript Global Meetup",
    image: "/images/event6.png",
    slug: "typescript-meetup",
    location: "London, UK",
    date: "2026-07-05",
    time: "06:00 PM",
  },
];
